const expressInterviewQuestions = [
  "What is Express.js?",
  "How do you install Express.js?",
  "How do you create a simple Express server?",
  "Explain the request–response lifecycle in Express.",
  "What is middleware in Express?",
  "How does middleware chaining work?",
  "What is the difference between application-level and router-level middleware?",
  "What is app.use()?",
  "What is the difference between app.use() and app.get()?",
  "What is next() in Express middleware?",
  "How do you parse JSON in Express?",
  "What are route parameters in Express?",
  "What is req.params?",
  "What is req.query?",
  "How do you handle POST data in Express?",
  "What are HTTP methods used in Express?",
  "What is res.send() vs res.json()?",
  "What is res.status()?",
  "How do you serve static files in Express?",
  "What is app.listen()?",
  "How do you create a router in Express?",
  "How do you use express.Router()?",
  "How do you pass data between middleware?",
  "How do you stop a request in middleware?",
  "How do you handle 404 errors in Express?",
  "How do you implement centralized error handling in Express?",
  "How do you handle global errors?",
  "How do you redirect in Express?",
  "How do you design RESTful APIs?",
  "What is the difference between REST and GraphQL?",
  "What is the difference between REST and RPC?",
  "How do you implement pagination in Express APIs?",
  "How do you implement filtering and sorting?",
  "What is API versioning and why is it important?",
  "What is idempotency in APIs?",
  "How do you implement authentication and authorization?",
  "What is the difference between authentication and authorization?",
  "What is JWT-based authentication?",
  "What is the difference between JWT-based and session-based authentication?",
  "How do you protect Express APIs from security vulnerabilities?",
  "What is rate limiting and how do you implement it?",
  "How do you handle file uploads securely in Express?",
  "How do you validate API inputs?",
  "What is input sanitization and why is it important?",
  "How do you log requests in Express?",
  "How do you log errors in production?",
  "What is Helmet and why is it used with Express?",
  "What is CORS and how do you configure it in Express?",
  "How do you make an Express application production-ready?",
];

export default expressInterviewQuestions;
