const interpersonalQuestions = [
  "Tell me about yourself?",
  "Tell me about your three weak points?",
  "What is your biggest strength?",
  "What was your biggest mistake in your life?",
  "Why should we hire you?",
  "Why are you suitable for the post?",
  "What is the skill that makes you different from others?",
  "What types of projects or technologies are you most excited to work on in the future?",
  "Can you describe a challenging project you've worked on recently? What technologies did you use, and how did you overcome any obstacles?",
  "How do you approach debugging and troubleshooting issues in your code?",
  "How do you ensure the security of the applications you develop?",
  "Can you share an example of how you handled security concerns in a past project?",
  "How do you handle stress and tight deadlines without compromising the quality of your work?",
  "Where do you see yourself in your career in the next two to five years?",
  "How do you handle situations where you encounter a problem for which you don't immediately have a solution?",
  "How do you stay motivated and engaged in your work over the long term?",
  "What's your approach to writing clean, maintainable, and efficient code?",
  "How do you collaborate with designers, backend developers, or other stakeholders to ensure a smooth workflow?",
  "Can you give an example of a time when you had to explain a technical concept to a non-technical team member or client?",
  "How do you prioritize tasks when working on multiple projects simultaneously?",
  "Have you ever disagreed with a teammate or manager on a technical decision? How did you handle it?",
  "What motivates you to continuously learn new frameworks or technologies?",
  "How do you balance speed of delivery with code quality in fast-paced environments?",
  "Tell me about a challenge you faced in a team project.",
  "How do you handle disagreements with teammates?",
  "Describe a time you missed a deadline.",
  "How do you handle ambiguity in requirements?",
  "Describe a time you received negative feedback.",
  "How do you balance code quality with tight deadlines?",
  "How do you handle feedback when your implementation is rejected during code review?",
  "How do you communicate complex technical issues to non-technical stakeholders?",
  "Describe a time you refactored someone else’s code. What was your approach?",
  "How do you ensure accountability when working in a team environment?",
  "What do you do when backend and frontend requirements conflict?",
  "Tell me about a time when you had to quickly adapt to a new technology or tool during a project.",
  "How do you ensure cross-team communication when working with remote or distributed teams?",
  "Describe your ideal work environment. What kind of team culture brings out your best work?",
  "How do you stay updated with the latest trends and technologies in web development?",
  "What role does user experience (UX) play in your approach to full-stack development?",
  "How do you handle feedback or criticism about your code or project decisions?",
  "What inspires you the most in your journey as a developer?",
];

export default interpersonalQuestions;
