const javascriptInterviewQuestions = [
  "What is JavaScript?",
  "Why is JavaScript a single-threaded language?",
  "Why is JavaScript considered an interpreted language?",
  "What is an Abstract Syntax Tree (AST)?",
  "What is JIT compilation in JavaScript?",
  "What is an execution context?",
  "What are the types of execution contexts?",
  "What is the call stack in JavaScript?",
  "How does JavaScript handle asynchronous code?",
  "What is the event loop?",
  "What is the difference between microtasks and macrotasks?",
  "How does JavaScript interact with HTML?",
  "How does JavaScript interact with CSS?",
  "Why do we need JavaScript along with HTML and CSS?",
  "What are the different data types in JavaScript?",
  "What is the difference between primitive and non-primitive data types?",
  "What is hoisting in JavaScript?",
  "What is the Temporal Dead Zone (TDZ)?",
  "What is the difference between var, let, and const?",
  "What are truthy and falsy values?",
  "What is scope in JavaScript?",
  "What is the difference between global, function, and block scope?",
  "What is a closure?",
  "How can closures cause memory leaks?",
  "What is garbage collection in JavaScript?",
  "How does the mark-and-sweep algorithm work?",
  "What is synchronous vs asynchronous JavaScript?",
  "What is a callback function?",
  "What is callback hell?",
  "What is a Promise?",
  "What are the states of a Promise?",
  "What is async/await?",
  "How does async/await work internally?",
  "How do you handle errors in async code?",
  "What is try-catch-finally?",
  "What is the this keyword in JavaScript?",
  "How does this behave in arrow functions?",
  "What are call, apply, and bind?",
  "What is Object-Oriented Programming (OOP)?",
  "Explain encapsulation, inheritance, polymorphism, and abstraction",
  "What is prototypal inheritance?",
  "What is the prototype chain?",
  "What is event bubbling and event capturing?",
  "What is event delegation?",
  "What is debouncing?",
  "What is throttling?",
  "What is immutability and why is it important?",
  "What causes reflow and repaint in browsers?",
  "What is memoization?",
  "What is currying?",
  "What is the difference between shallow copy and deep copy?",
  "How do you deep clone an object in JavaScript?",
  "What are ES6 features commonly used?",
  "What are rest and spread operators?",
  "What is destructuring?",
  "What are default parameters?",
  "What is optional chaining?",
  "What is nullish coalescing?",
  "What is the difference between == and ===?",
  "Why is NaN considered special in JavaScript?",
  "What is the difference between map, forEach, filter, and reduce?",
  "What is the difference between find and filter?",
  "What is the difference between includes and indexOf?",
  "What are generators and iterators?",
  "What is a pure function?",
  "What is an impure function?",
  "What are higher-order functions?",
  "What is recursion?",
  "What is an IIFE?",
  "What is the difference between ES Modules and CommonJS?",
  "How does JavaScript run in the browser vs Node.js?",
  "What are Web APIs?",
  "What is JSON?",
  "How do you convert data between JSON and objects?",
  "What is a memory leak?",
  "What are common JavaScript performance optimization techniques?",
  "What is rate limiting and throttling (conceptually)?",
  "What is idempotency?",
  "What are common JavaScript interview problem-solving patterns?",
];

export default javascriptInterviewQuestions;
