const nextJsInterviewQuestions = [
  "What is Next.js?",
  "Why should we use Next.js instead of React?",
  "What are the main features of Next.js?",
  "What is file-based routing in Next.js?",
  "What is the difference between Pages Router and App Router?",
  "What types of rendering are supported in Next.js?",
  "What is Static Site Generation (SSG)?",
  "What is Server-Side Rendering (SSR)?",
  "What is Client-Side Rendering (CSR)?",
  "What is Incremental Static Regeneration (ISR)?",
  "What are the benefits and limitations of SSG?",
  "What are the benefits and limitations of SSR?",
  "When should you use ISR?",
  "What is hydration in Next.js?",
  "What causes hydration mismatch errors?",
  "How does Next.js improve SEO by default?",
  "What is getStaticProps?",
  "What is getServerSideProps?",
  "What is getStaticPaths?",
  "What is the difference between getStaticProps and getServerSideProps?",
  "What are dynamic routes in Next.js?",
  "What are catch-all and optional catch-all routes?",
  "What is the app directory in Next.js?",
  "What is page.js in the App Router?",
  "What is layout.js and how does it work?",
  "What is template.js and how is it different from layout.js?",
  "What are Server Components in Next.js?",
  "What are Client Components in Next.js?",
  "When should you use 'use client'?",
  "What are API routes in Next.js?",
  "What is Middleware in Next.js?",
  "What is the difference between Middleware and API routes?",
  "How does authentication work in Next.js?",
  "Where should JWT verification happen in Next.js?",
  "How do you protect server-only logic in Next.js?",
  "How does data fetching work in App Router?",
  "How does caching work in Next.js?",
  "What are the different caching layers in Next.js?",
  "What is revalidation and how does it work?",
  "What is revalidatePath?",
  "What is revalidateTag?",
  "What is Streaming in Next.js?",
  "How does Suspense work with streaming?",
  "What is next/link used for?",
  "What is next/router or useRouter used for?",
  "What is useParams and how is it different from useRouter?",
  "What is next/image and why is it better than <img>?",
  "What is next/font?",
  "How do you handle environment variables in Next.js?",
  "What is NEXT_PUBLIC_ prefix used for?",
  "What is code splitting in Next.js?",
  "How does Next.js improve performance?",
  "What is lazy loading in Next.js?",
  "How do you optimize images and fonts in Next.js?",
  "How does Next.js handle large traffic spikes?",
  "What are Server Actions in Next.js?",
  "Why are Server Actions more secure than API routes?",
  "How do you handle form submissions in Next.js App Router?",
  "What is useTransition in Next.js?",
  "What is useActionState?",
  "What causes slow TTFB and how do you reduce it?",
  "How do you debug a Next.js app after deployment?",
  "What are common Next.js production issues?",
  "How do you optimize Core Web Vitals in Next.js?",
  "When would you choose Next.js over other frameworks?",
];

export default nextJsInterviewQuestions;
