const nodeInterviewQuestions = [
  "What is Node.js?",
  "What is the difference between Node.js and JavaScript?",
  "What is the difference between window in the browser and global in Node.js?",
  "What is a module in Node.js?",
  "What is npm?",
  "What is package.json?",
  "What is the difference between CommonJS and ES Modules?",
  "What is the event loop in Node.js?",
  "How does Node.js work internally (event loop and non-blocking I/O)?",
  "How does Node.js handle concurrent requests?",
  "What happens when the event loop is blocked?",
  "What are streams in Node.js?",
  "What are the types of streams?",
  "What is the difference between Buffer and Stream?",
  "What causes memory leaks in Node.js?",
  "How do you debug a memory leak in Node.js?",
  "What is clustering in Node.js?",
  "What are worker threads?",
  "What is the use of the Buffer class?",
  "What is EventEmitter?",
  "What is middleware in Express.js?",
  "What is callback hell?",
  "How do you avoid callback hell in modern Node.js?",
  "What are promises in Node.js?",
  "What is async/await?",
  "What is the difference between synchronous and asynchronous functions?",
  "How do you handle errors in async functions?",
  "What is JWT and how does it work?",
  "What is authentication and authorization?",
  "What is CORS?",
  "How do you manage environment variables in Node.js?",
  "What is the difference between PUT and PATCH?",
  "What is module.exports?",
  "What is Helmet in Node.js?",
  "What is Nodemon?",
  "How do you connect MongoDB in Node.js?",
  "How do you handle file uploads in Node.js?",
  "How do you secure a Node.js API?",
  "What is rate limiting and why is it important?",
  "What is API idempotency?",
  "What is PM2 and why is it used?",
  "How do you keep a Node.js process running in production?",
  "How does require cache work in Node.js?",
  "Can you mix CommonJS and ES Modules?",
  "How do you handle uncaught exceptions?",
  "How do you handle unhandled promise rejections?",
  "What is graceful shutdown in Node.js?",
  "What is the difference between __dirname and process.cwd()?",
  "What is backpressure in streams?",
  "What is the difference between REST and RESTful API?",
  "What is the difference between monolithic and microservices architecture?",
  "What is load balancing?",
  "What is Redis and why is it used?",
  "What is caching?",
  "What is WebSocket?",
  "What is the difference between GraphQL and REST?",
  "What is a reverse proxy?",
  "What is the difference between horizontal and vertical scaling?",
];

export default nodeInterviewQuestions;
