const reactInterviewQuestions = [
  "What is React?",
  "Why is React used instead of plain JavaScript?",
  "What is the Virtual DOM?",
  "How does React’s reconciliation process work?",
  "What are React components?",
  "What are functional components?",
  "What are class components?",
  "What is the difference between class and functional components?",
  "What is JSX?",
  "How does JSX work under the hood?",
  "What are props in React?",
  "What is state in React?",
  "What is the difference between state and props?",
  "What happens when state changes?",
  "Why shouldn’t we mutate state directly?",
  "What are React Hooks?",
  "What is useState?",
  "Why are useState updates asynchronous?",
  "What is batching in React?",
  "What is useEffect?",
  "What are side effects in React?",
  "How does the dependency array in useEffect work?",
  "How do you prevent memory leaks in useEffect?",
  "What is a stale closure in React?",
  "What is useRef and when should you use it?",
  "What is the difference between useRef and useState?",
  "How do you access DOM elements in React?",
  "What is useLayoutEffect?",
  "What is the difference between useEffect and useLayoutEffect?",
  "What is useMemo?",
  "When should you use useMemo?",
  "What is useCallback?",
  "Why is referential equality important in React?",
  "What is React.memo?",
  "How does React.memo work internally?",
  "What causes unnecessary re-renders?",
  "How do you prevent unnecessary re-renders?",
  "What are keys in React and why are they important?",
  "What happens if keys are not stable?",
  "What are React fragments?",
  "What is conditional rendering?",
  "What is lifting state up?",
  "What is React Context?",
  "What problem does Context API solve?",
  "What are the drawbacks of using Context for everything?",
  "What is prop drilling?",
  "What are controlled components?",
  "What are uncontrolled components?",
  "What is the difference between controlled and uncontrolled components?",
  "How do you handle form validation in React?",
  "What is useReducer?",
  "When should you use useReducer instead of useState?",
  "Does useReducer improve performance?",
  "What is useTransition?",
  "How does useTransition improve UI responsiveness?",
  "What is useActionState?",
  "How does useActionState simplify form handling?",
  "What are Server Actions in React?",
  "What is the use hook in React?",
  "How does the use hook work with Suspense?",
  "What is Suspense in React?",
  "What happens when a promise passed to use rejects?",
  "What is lazy loading in React?",
  "How does React.lazy work?",
  "What is code splitting?",
  "What is a Higher-Order Component (HOC)?",
  "What problems can HOCs cause?",
  "What are pure components?",
  "What is memoization in React?",
  "What are presentational vs container components?",
  "What are stateful vs stateless components?",
  "What is the Compound Component pattern?",
  "What are render props?",
  "What is the difference between custom hooks and HOCs?",
  "How does React skip re-rendering?",
  "What is Strict Mode in React?",
  "Why does Strict Mode run effects twice in development?",
  "How do you debug performance issues in React?",
  "How do you debug memory leaks in React?",
  "What are Error Boundaries?",
  "How do you handle global errors in React apps?",
  "How do you optimize large forms in React?",
  "How do you share state between deeply nested components?",
  "When would you use Redux or Zustand instead of Context?",
];

export default reactInterviewQuestions;
