const reduxInterviewQuestions = [
  "What is Redux?",
  "Why do we need Redux?",
  "What problems does Redux solve?",
  "What are the core principles of Redux?",
  "What does single source of truth mean?",
  "Why is Redux state read-only?",
  "What is a Redux store?",
  "What is an action in Redux?",
  "What is an action creator?",
  "What must an action object contain?",
  "What is dispatch in Redux?",
  "What is a reducer?",
  "Why must reducers be pure functions?",
  "Why should reducers never mutate state?",
  "What is immutability and why is it important in Redux?",
  "What happens if you mutate state directly?",
  "What is the Redux data flow?",
  "How does Redux work with React?",
  "What is react-redux?",
  "What is the Provider component?",
  "What is useSelector?",
  "What is useDispatch?",
  "How does useSelector trigger re-renders?",
  "What are selectors in Redux?",
  "Why should you use selectors?",
  "What is middleware in Redux?",
  "Why does Redux need middleware?",
  "What is Redux Thunk?",
  "How does Redux Thunk handle async actions?",
  "What problem does Redux Thunk solve?",
  "What is Redux Toolkit (RTK)?",
  "Why is Redux Toolkit recommended?",
  "What is configureStore?",
  "What is createSlice?",
  "How does createSlice reduce boilerplate?",
  "What is Immer and how does it work?",
  "What is createAsyncThunk?",
  "What actions does createAsyncThunk generate?",
  "What is extraReducers?",
  "How do you handle loading and error states in Redux?",
  "What is RTK Query?",
  "Why is RTK Query better for data fetching?",
  "How does RTK Query handle caching?",
  "What is automatic re-fetching in RTK Query?",
  "What are tags and invalidation in RTK Query?",
  "What is polling in RTK Query?",
  "What is selectFromResult?",
  "How does selectFromResult reduce re-renders?",
  "What is redux-persist?",
  "How do you persist Redux state across refresh?",
  "Redux vs Context API – when to use which?",
  "Redux vs useReducer – what are the differences?",
  "What should go into Redux state?",
  "When should Redux NOT be used?",
  "How do you structure large Redux applications?",
  "What are feature-based folders in Redux?",
  "How do you handle side effects in Redux?",
  "How do you prevent race conditions in Redux?",
  "How do you cancel async requests in Redux?",
  "Why might Redux cause performance issues?",
  "How do selectors help with performance?",
  "What causes unnecessary re-renders in Redux?",
  "What is Redux DevTools?",
  "How do Redux DevTools help debugging?",
  "How do you test reducers?",
  "How do you test async thunks?",
  "What is the difference between RTK Query and createAsyncThunk?",
  "How do you handle multiple components using the same API data?",
  "What happens if two async actions update the same state?",
  "Why might a Redux state update not trigger re-render?",
  "How do you debug Redux state issues?",
];

export default reduxInterviewQuestions;
