const typescriptInterviewQuestions = [
  "What is TypeScript?",
  "Why do we use TypeScript?",
  "Who developed TypeScript?",
  "Can browsers run TypeScript directly?",
  "How do you compile TypeScript code?",
  "What is tsconfig.json?",
  "What is strict mode in TypeScript?",
  "What is a type in TypeScript?",
  "What are basic data types in TypeScript?",
  "What is the any type?",
  "What is the difference between any and unknown?",
  "What is type inference?",
  "What is a union type?",
  "What is an intersection type?",
  "What is a type alias?",
  "What is an interface?",
  "What is the difference between interface and type?",
  "What is the difference between interface and class?",
  "What are generics in TypeScript?",
  "Why are generics useful?",
  "What is an enum?",
  "What is a tuple?",
  "What is the void type?",
  "What is the never type?",
  "What are optional properties in TypeScript?",
  "What does readonly mean in TypeScript?",
  "What are access modifiers in TypeScript?",
  "What is type assertion?",
  "What is type narrowing?",
  "What are type guards?",
  "What are utility types in TypeScript?",
  "What is Partial<T>?",
  "What is Pick<T, K>?",
  "What is Readonly<T>?",
  "What is Required<T>?",
  "What is Omit<T, K>?",
  "How do you define a function in TypeScript?",
  "How do you type function parameters and return types?",
  "What is a class in TypeScript?",
  "What is inheritance in TypeScript?",
  "What is a module in TypeScript?",
  "How do export and import work in TypeScript?",
  "What are decorators in TypeScript?",
  "What is structural typing?",
  "What is nominal vs structural typing?",
  "How does TypeScript improve large-scale applications?",
  "What are common advantages of TypeScript over JavaScript?",
  "What are some common TypeScript compile-time errors?",
  "How does TypeScript help with better tooling and IntelliSense?",
];

export default typescriptInterviewQuestions;
